version: '2'
services:
  simplesamlphp:
    image: uzzal2k5/simplesaml:latest
    container_name: simplesaml
    hostname: simplesaml
    volumes:
    #- ./data/simplesamlphp-1.13.2:/var/simplesamlphp
    #- ./data/simplesamlphp-1.14.11:/var/simplesamlphp
    - ./data/simplesamlphp-overwrites:/opt/simplesamlphp-overwrites
    ports:
    - 8080:80