version: '2'
services:
  ndn-box-sp:
    image: saml:latest
    volumes:
    #- ./data/simplesamlphp-1.13.2:/var/simplesamlphp
    #- ./data/simplesamlphp-1.14.11:/var/simplesamlphp
    - ./data/simplesamlphp-overwrites:/opt/simplesamlphp-overwrites
    ports:
    - 8080:80