version: '2.0'
services:
  simplesaml:
    image: simplesaml:latest
    #build:
    #  dockerfile: Dockerfile
    container_name: simplesaml
    hostname: simplesaml
    volumes:
      - ${PWD}/logs:/var/log
    ports:
      - "80:80"
